#!/usr/bin/env python3
"""Generate contract files for atomic skills from a workflow spec.

Usage:
    python3 generate-contract.py workflow.json --output-dir ./contracts

Input format (workflow.json):
{
  "workflow_name": "content-collection",
  "atomic_skills": [
    {
      "name": "parse-author",
      "responsibility": "Extract author metadata from platform profile",
      "input": {
        "required": {"url": "string"},
        "optional": {"depth": "number (default 1)"}
      },
      "output": {
        "author_name": "string",
        "author_id": "string",
        "follower_count": "number"
      },
      "preconditions": ["network access", "platform API credentials"],
      "failure_behavior": {
        "timeout": "retry 2x with exponential backoff",
        "auth_error": "stop and report",
        "not_found": "return {status: not_found}"
      },
      "verification": "output.author_id is non-empty string"
    }
  ]
}

Output: One contract.md file per skill in the output directory.
"""

import json
import sys
import os
from pathlib import Path


def generate_contract_md(skill: dict, workflow_name: str) -> str:
    name = skill["name"]
    
    # Input table
    input_rows = []
    for field, ftype in skill.get("input", {}).get("required", {}).items():
        input_rows.append(f"| `{field}` | {ftype} | Yes | - |")
    for field, ftype in skill.get("input", {}).get("optional", {}).items():
        # Extract default from type string if present
        default = "-"
        if "(default" in ftype:
            default = ftype.split("(default")[1].rstrip(")")
            ftype = ftype.split("(default")[0].strip()
        input_rows.append(f"| `{field}` | {ftype} | No | {default} |")
    input_table = "\n".join(input_rows) if input_rows else "| (none) | - | - | - |"
    
    # Output table
    output_rows = []
    for field, ftype in skill.get("output", {}).items():
        output_rows.append(f"| `{field}` | {ftype} |")
    output_table = "\n".join(output_rows) if output_rows else "| (none) | - |"
    
    # Preconditions
    preconds = skill.get("preconditions", [])
    precond_list = "\n".join(f"- {p}" for p in preconds) if preconds else "- (none)"
    
    # Failure behavior table
    failure_rows = []
    for signal, response in skill.get("failure_behavior", {}).items():
        failure_rows.append(f"| `{signal}` | {response} |")
    failure_table = "\n".join(failure_rows) if failure_rows else "| (none) | (none) |"
    
    # Verification
    verification = skill.get("verification", "Output matches schema above.")
    
    contract_version = skill.get("contract_version", "1.0")
    
    return f"""# Contract: {name}

> Workflow: {workflow_name}  
> Contract version: {contract_version}  
> Generated by: generate-contract.py

## Responsibility

{skill.get("responsibility", "(not specified)")}

## Input

| Field | Type | Required | Default |
|-------|------|----------|---------|
{input_table}

### Example input

```json
{json.dumps({k: f"<{v}>" for k, v in skill.get("input", {}).get("required", {}).items()}, indent=2)}
```

## Output

| Field | Type |
|-------|------|
{output_table}

### Example output

```json
{json.dumps({k: f"<{v}>" for k, v in skill.get("output", {}).items()}, indent=2)}
```

## Preconditions

{precond_list}

## Failure Behavior

| Signal | Response |
|--------|----------|
{failure_table}

## Verification

{verification}

## Changelog

- v{contract_version}: Initial contract.
"""


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate-contract.py workflow.json [--output-dir DIR]")
        print(__doc__)
        sys.exit(1)
    
    spec_path = sys.argv[1]
    output_dir = "./contracts"
    
    if "--output-dir" in sys.argv:
        idx = sys.argv.index("--output-dir")
        if idx + 1 < len(sys.argv):
            output_dir = sys.argv[idx + 1]
    
    with open(spec_path) as f:
        spec = json.load(f)
    
    workflow_name = spec.get("workflow_name", "unnamed-workflow")
    skills = spec.get("atomic_skills", [])
    
    if not skills:
        print("Error: No atomic_skills found in spec.")
        sys.exit(1)
    
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    
    generated = []
    for skill in skills:
        name = skill["name"]
        contract_md = generate_contract_md(skill, workflow_name)
        out_path = os.path.join(output_dir, f"{name}-contract.md")
        with open(out_path, "w") as f:
            f.write(contract_md)
        generated.append(out_path)
        print(f"  Generated: {out_path}")
    
    print(f"\nDone. {len(generated)} contract(s) written to {output_dir}/")


if __name__ == "__main__":
    main()
