#!/usr/bin/env python3
import argparse, html, json
from pathlib import Path

def esc(value): return html.escape(str(value), quote=True)

def option_rows(options, group):
    return "".join(f'<label class="option"><input type="radio" name="{esc(group)}" value="{esc(k)}"><span><b>{esc(k)}.</b> {esc(v)}</span></label>' for k,v in options.items())

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--input',required=True); ap.add_argument('--output',required=True); args=ap.parse_args()
    d=json.loads(Path(args.input).read_text(encoding='utf-8'))
    sections=''.join(f'<section id="{esc(s["id"])}"><h2>{esc(s["title"])}</h2>{s["html"]}</section>' for s in d['sections'])
    nav=''.join(f'<a href="#{esc(s["id"])}">{esc(s["title"])}</a>' for s in d['sections'])
    diagnosis=json.dumps(d.get('diagnosis',{}),ensure_ascii=False).replace('</','<\\/')
    practices=[]; pnav=[]
    for i,p in enumerate(d.get('practice',[]),1):
        pid=f'practice-{i}'; pnav.append(f'<a href="#{pid}">练习 {i} · {esc(p.get("tag","重构题"))}</a>')
        practices.append(f'''<section id="{pid}" class="quiz practice" data-answer="{esc(p['answer'])}" data-explanation="{esc(p['explanation'])}"><div class="tag">{esc(p.get('tag','重构题'))}</div><h2>重构练习 {i}</h2><p class="question">{esc(p['question'])}</p><div class="options">{option_rows(p['options'],pid)}</div><div class="actions"><button class="submit">提交答案</button><button class="reset secondary">重新作答</button></div><div class="feedback" role="status" aria-live="polite"></div></section>''')
    out=Path(args.output); out.parent.mkdir(parents=True,exist_ok=True)
    doc=f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(d['title'])}</title><style>
:root{{--bg:#f5f3ee;--paper:#fffefa;--ink:#24231f;--muted:#6d695f;--accent:#b64b2a;--accent2:#1f6b63;--line:#ded9cf;--ok:#176b45;--bad:#a7332d;--mark:#ffe58a}}*{{box-sizing:border-box}}html{{scroll-behavior:smooth}}body{{margin:0;background:var(--bg);color:var(--ink);font:16px/1.75 system-ui,-apple-system,"PingFang SC","Microsoft YaHei",sans-serif}}aside{{position:fixed;inset:0 auto 0 0;width:280px;padding:28px 20px;background:#24231f;color:#fff;overflow:auto}}aside h1{{font-size:20px;line-height:1.35}}aside .meta{{color:#c7c0b4;font-size:13px}}nav a{{display:block;color:#ddd5c8;text-decoration:none;padding:8px 10px;border-left:3px solid transparent}}nav a.active{{color:#fff;background:#ffffff12;border-left-color:#f0a269}}.progress{{height:7px;background:#ffffff22;border-radius:9px;overflow:hidden;margin:18px 0}}.progress span{{display:block;height:100%;width:0;background:#f0a269;transition:.3s}}main{{margin-left:280px;max-width:1000px;padding:42px 7vw 90px}}section{{background:var(--paper);border:1px solid var(--line);border-radius:16px;padding:28px;margin:0 0 24px;box-shadow:0 8px 24px #3f342214}}h2{{line-height:1.3;margin-top:0}}h3{{color:var(--accent2)}}mark{{background:var(--mark);padding:.05em .2em}}blockquote{{border-left:4px solid var(--accent);margin-left:0;padding:8px 18px;background:#fff5ed}}table{{border-collapse:collapse;width:100%}}th,td{{border:1px solid var(--line);padding:9px;text-align:left}}.tag{{display:inline-block;color:var(--accent);background:#fae9df;border-radius:99px;padding:2px 10px;font-size:13px}}.question{{font-size:18px;font-weight:650}}.option{{display:flex;gap:10px;padding:11px;margin:8px 0;border:1px solid var(--line);border-radius:10px;cursor:pointer}}.option:has(input:checked){{border-color:var(--accent2);background:#eaf5f2}}button{{border:0;border-radius:9px;padding:10px 17px;background:var(--accent2);color:white;font-weight:700;cursor:pointer}}button.secondary{{background:#ded9cf;color:var(--ink)}}button:focus-visible,input:focus-visible,a:focus-visible{{outline:3px solid #f0a269;outline-offset:3px}}.actions{{display:flex;gap:10px;margin-top:16px}}.feedback{{display:none;margin-top:16px;padding:13px;border-radius:10px}}.feedback.ok{{display:block;background:#e8f5ed;color:var(--ok)}}.feedback.bad{{display:block;background:#fae9e7;color:var(--bad)}}#analysis-wrap{{display:none}}body.revealed #analysis-wrap{{display:block}}#mastery{{display:none;background:#e8f5ed;color:var(--ok);font-weight:800}}body.complete #mastery{{display:block}}@media(max-width:800px){{aside{{position:relative;width:auto;max-height:320px}}main{{margin:0;padding:20px}}section{{padding:20px}}}}
</style></head><body><aside><h1>{esc(d['title'])}</h1><div class="meta">{esc(d.get('category','公考题目精讲'))}</div><div class="progress"><span id="bar"></span></div><div class="meta" id="progress-text">学习进度 0%</div><nav><a href="#original">原题测试</a>{nav}{''.join(pnav)}<a href="#mastery">掌握状态</a></nav></aside><main>
<section id="original" class="quiz" data-answer="{esc(d['answer'])}"><div class="tag">先测后学</div><h2>原题测试</h2><p class="question">{esc(d['question'])}</p><div class="options">{option_rows(d['options'],'original')}</div><div class="actions"><button class="submit">提交答案</button><button class="reset secondary">重新作答</button><button id="enter" style="display:none">进入解析</button></div><div class="feedback" role="status" aria-live="polite"></div></section>
<div id="analysis-wrap">{sections}{''.join(practices)}<section id="mastery">🎉 本轮掌握完成：你已经完成原题与全部重构练习。</section></div></main><script>
const diagnoses={diagnosis}; const quizzes=[...document.querySelectorAll('.quiz')]; const done=new Set();
function update(){{let pct=Math.round(done.size/quizzes.length*100);document.querySelector('#bar').style.width=pct+'%';document.querySelector('#progress-text').textContent='学习进度 '+pct+'%';document.body.classList.toggle('complete',done.size===quizzes.length)}}
quizzes.forEach(q=>{{q.querySelector('.submit').onclick=()=>{{let pick=q.querySelector('input:checked'),f=q.querySelector('.feedback');if(!pick){{f.className='feedback bad';f.textContent='请先选择一个答案。';return}}let ok=pick.value===q.dataset.answer;let detail=q.id==='original'?(diagnoses[pick.value]||''):q.dataset.explanation;f.className='feedback '+(ok?'ok':'bad');f.innerHTML=(ok?'回答正确。':'回答错误，正确答案是 '+q.dataset.answer+'。')+(detail?'<br>'+detail:'');done.add(q.id);if(q.id==='original'){{document.body.classList.add('revealed');document.querySelector('#enter').style.display='inline-block'}}update()}};q.querySelector('.reset').onclick=()=>{{q.querySelectorAll('input').forEach(x=>x.checked=false);let f=q.querySelector('.feedback');f.className='feedback';f.textContent='';done.delete(q.id);if(q.id==='original'){{document.body.classList.remove('revealed');document.querySelector('#enter').style.display='none'}}update()}}}});
document.querySelector('#enter').onclick=()=>document.querySelector('#analysis-wrap section').scrollIntoView();
const links=[...document.querySelectorAll('nav a')];let obs=new IntersectionObserver(es=>es.forEach(e=>{{if(e.isIntersecting){{links.forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))}}}}),{{rootMargin:'-20% 0px -70%'}});document.querySelectorAll('section').forEach(s=>obs.observe(s));update();
</script></body></html>'''
    out.write_text(doc,encoding='utf-8')

if __name__=='__main__': main()
